"""Init

Revision ID: 7b87cd52eaf0
Revises: 
Create Date: 2024-09-29 14:08:20.811636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b87cd52eaf0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=50), nullable=False),
    sa.Column('product_description', sa.String(length=250), nullable=False),
    sa.Column('product_cost', sa.String(length=10), nullable=False),
    sa.Column('product_cost_d', sa.String(length=10), nullable=False),
    sa.Column('date_create', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_update', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=100), nullable=False),
    sa.Column('user_name', sa.String(length=30), nullable=False),
    sa.Column('user_first_name', sa.String(length=30), nullable=True),
    sa.Column('user_last_name', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('phone_number', sa.String(length=50), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='roles'), nullable=False),
    sa.Column('date_create', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_update', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('date_create', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_update', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['catalog.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('extra_data', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['catalog.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders_products')
    op.drop_table('orders')
    op.drop_table('users')
    op.drop_table('catalog')
    # ### end Alembic commands ###
