"""Initial

Revision ID: d3f1da50b78a
Revises: cf2e8ff7287d
Create Date: 2025-10-04 19:35:20.932895

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d3f1da50b78a"
down_revision: Union[str, None] = "cf2e8ff7287d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "poll",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.String(length=100), nullable=False),
        sa.Column("title", sa.String(length=150), nullable=True),
        sa.Column("type", sa.String(length=10), nullable=True),
        sa.Column("v", sa.Integer(), nullable=True),
        sa.Column("question", sa.String(length=300), nullable=True),
        sa.Column("answer", sa.Integer(), nullable=True),
        sa.Column(
            "date_create",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_anonymous", sa.Boolean(), nullable=False),
        sa.Column("date_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("date_end", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pollanswer",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("poll_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(length=100), nullable=False),
        sa.Column("user_answer", sa.Integer(), nullable=False),
        sa.Column("poll_end", sa.Boolean(), nullable=False),
        sa.Column(
            "date_poll",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pollanswer")
    op.drop_table("poll")
    # ### end Alembic commands ###
