"""Initial

Revision ID: 4388538a2508
Revises: 24cfa1084b01
Create Date: 2025-06-09 16:53:12.213069

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4388538a2508"
down_revision: Union[str, None] = "24cfa1084b01"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("quiz_uuid_key", "quiz", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("quiz_uuid_key", "quiz", ["uuid"])
    # ### end Alembic commands ###
