"""Initial

Revision ID: 9ffe544689df
Revises: 4388538a2508
Create Date: 2025-06-09 17:09:37.393429

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9ffe544689df"
down_revision: Union[str, None] = "4388538a2508"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "quiz_options",
        sa.Column("answer", sa.String(length=150), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("quiz_options", "answer")
    # ### end Alembic commands ###
