"""Initial

Revision ID: e784bcb6a3cb
Revises: eb182f65a075
Create Date: 2025-09-24 10:28:06.416230

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e784bcb6a3cb"
down_revision: Union[str, None] = "eb182f65a075"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mediacontent",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("file_id", sa.String(length=100), nullable=False),
        sa.Column("file_caption", sa.String(length=100), nullable=False),
        sa.Column("file_type", sa.String(length=2), nullable=False),
        sa.Column("file_name", sa.String(length=50), nullable=False),
        sa.Column("uuid_user_upload", sa.String(length=100), nullable=False),
        sa.Column(
            "date_create",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "date_send",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("file_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("mediacontent")
    # ### end Alembic commands ###
