"""Initial

Revision ID: cf2e8ff7287d
Revises: e784bcb6a3cb
Create Date: 2025-10-01 18:05:32.489984

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cf2e8ff7287d"
down_revision: Union[str, None] = "e784bcb6a3cb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("quiz", sa.Column("v", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("quiz", "v")
    # ### end Alembic commands ###
