"""add gender 

Revision ID: e9dbb85e993a
Revises: 14158a2601b6
Create Date: 2025-02-21 21:30:20.883314

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e9dbb85e993a"
down_revision: Union[str, None] = "14158a2601b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("FEMALE", "MALE", name="genders").create(op.get_bind())
    op.add_column(
        "users",
        sa.Column(
            "gender",
            postgresql.ENUM(
                "FEMALE", "MALE", name="genders", create_type=False
            ),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "gender")
    sa.Enum("FEMALE", "MALE", name="genders").drop(op.get_bind())
    # ### end Alembic commands ###
